name: Nightly CSV Backup

on:
  workflow_dispatch:   # correct spelling for manual runs
  schedule:
    - cron: "0 16 * * *"   # 00:00 Asia/Manila (~16:00 UTC)

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || npm i

      - name: Run backup script
        run: node scripts/backup.mjs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Commit CSVs
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add exports/*.csv || true
          git commit -m "nightly backup $(date -u +%Y-%m-%dT%H:%M:%SZ)" || echo "no c$
          git push https://$GH_PAT@github.com/kmnzd-hash/royalty-bundle-v1.git HEAD:m$



