name: sync-and-backup

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # daily 02:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Run sync (Notion <> Supabase)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_BUNDLES: ${{ secrets.NOTION_DB_BUNDLES }}
          NOTION_DB_SALES: ${{ secrets.NOTION_DB_SALES }}
          NOTION_DB_PAYOUTS: ${{ secrets.NOTION_DB_PAYOUTS }}
          NOTION_DB_DASHBOARD: ${{ secrets.NOTION_DB_DASHBOARD }}
        run: |
          node scripts/sync.mjs
      - name: Backup CSVs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node scripts/backup.mjs
      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-backup
          path: exports/
